spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/weekly_report_db
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

server:
  port: 8080